server:
  name: user_service  # 服务名称
  address: 127.0.0.1  # 服务地址
  port: 10000  # 服务端口


mysql:
  driver: mysql
  host: 127.0.0.1
  port: 3306
  username: root
  password: 123456
  database: tiny_tiktok


etcd:
  address: 127.0.0.1
  port: 2379